# Generated by Django 3.1.7 on 2022-03-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=50)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
